Switch to dev.power.usage_count.
Kernels >3.16.71 removed pm_usage_cnt from usb_interface, resulting in "error: ‘struct usb_interface’ has no member named ‘pm_usage_cnt’". Updated to 'dev.power.usage_count'.